# This is a basic workflow to help you get started with Actions

name: CI booking

on:
 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

 
jobs:
   build:
   
    runs-on: ubuntu-latest

   
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

   test:
   
    runs-on: ubuntu-latest

   
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          cache: maven
      - name: Run Unit Tests
        run: mvn test  
