# This is a basic workflow to help you get started with Actions

name: CI booking

on:
 
  pull_request:
    types:
      - opened
    branches:
      - 'develop'

 
jobs:
   build:
   
    runs-on: ubuntu-latest

   
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Run Unit Tests
        run: mvn test  

  
